/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var aa;if(void 0!==this)aa=this;else if("undefined"!=typeof global)aa=global;else{if("undefined"==typeof self)throw new Error("Can't find global scope");aa=self};function k(a,c){function b(){}b.prototype=c.prototype;a.Ja=c.prototype;a.prototype=new b;a.prototype.constructor=a;a.Qa=function(d,e,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return c.prototype[e].apply(d,g)}};function l(a,c){null!=a&&this.append.apply(this,arguments)}l.prototype.l="";l.prototype.set=function(a){this.l=""+a};l.prototype.append=function(a,c,b){this.l+=String(a);if(null!=c)for(var d=1;d<arguments.length;d++)this.l+=arguments[d];return this};l.prototype.clear=function(){this.l=""};l.prototype.toString=function(){return this.l};var ba=Array.prototype.indexOf?function(a,c,b){return Array.prototype.indexOf.call(a,c,b)}:function(a,c,b){b=null==b?0:0>b?Math.max(0,a.length+b):b;if("string"===typeof a)return"string"!==typeof c||1!=c.length?-1:a.indexOf(c,b);for(;b<a.length;b++)if(b in a&&a[b]===c)return b;return-1},ca=Array.prototype.filter?function(a,c){return Array.prototype.filter.call(a,c,void 0)}:function(a,c){for(var b=a.length,d=[],e=0,f="string"===typeof a?a.split(""):a,g=0;g<b;g++)if(g in f){var h=f[g];c.call(void 0,
h,g,a)&&(d[e++]=h)}return d};function da(a,c){a.sort(c||ea)}function ea(a,c){return a>c?1:a<c?-1:0};function fa(a){var c=[],b=0,d;for(d in a)c[b++]=a[d];return c};function ha(a,c){this.$=a;this.qa=!!c.oa;this.da=c.g;this.Aa=c.type;this.va=!1;switch(this.da){case ia:case ja:case ka:case la:case ma:case na:case oa:this.va=!0}this.la=c.defaultValue}var oa=1,na=2,ia=3,ja=4,ka=6,la=16,ma=18;function pa(a,c){this.Ga=a;this.ca={};for(var b=0;b<c.length;b++){var d=c[b];this.ca[d.$]=d}}function qa(a){a=fa(a.ca);da(a,function(c,b){return c.$-b.$});return a};function n(){this.s={};this.ca=this.j().ca;this.m=this.za=null}n.prototype.has=function(a){return p(this,a.$)};n.prototype.get=function(a,c){return q(this,a.$,c)};n.prototype.set=function(a,c){r(this,a.$,c)};n.prototype.add=function(a,c){ra(this,a.$,c)};n.prototype.clear=function(a){a=a.$;delete this.s[a];this.m&&delete this.m[a]};
function sa(a,c){for(var b=qa(a.j()),d=0;d<b.length;d++){var e=b[d],f=e.$;if(p(c,f)){a.m&&delete a.m[e.$];var g=11==e.da||10==e.da;if(e.qa){e=t(c,f);for(var h=0;h<e.length;h++)ra(a,f,g?e[h].clone():e[h])}else e=u(c,f),g?(g=u(a,f))?sa(g,e):r(a,f,e.clone()):r(a,f,e)}}}n.prototype.clone=function(){var a=new this.constructor;a!=this&&(a.s={},a.m&&(a.m={}),sa(a,this));return a};function p(a,c){return null!=a.s[c]}
function u(a,c){var b=a.s[c];if(null==b)return null;if(a.za){if(!(c in a.m)){var d=a.za,e=a.ca[c];if(null!=b)if(e.qa){for(var f=[],g=0;g<b.length;g++)f[g]=d.pa(e,b[g]);b=f}else b=d.pa(e,b);return a.m[c]=b}return a.m[c]}return b}function q(a,c,b){var d=u(a,c);return a.ca[c].qa?d[b||0]:d}
function v(a,c){if(p(a,c))var b=q(a,c,void 0);else a:{b=a.ca[c];if(void 0===b.la){var d=b.Aa;if(d===Boolean)b.la=!1;else if(d===Number)b.la=0;else if(d===String)b.la=b.va?"0":"";else{b=new d;break a}}b=b.la}return b}function t(a,c){return u(a,c)||[]}function w(a,c){return a.ca[c].qa?p(a,c)?a.s[c].length:0:p(a,c)?1:0}function r(a,c,b){a.s[c]=b;a.m&&(a.m[c]=b)}function ra(a,c,b){a.s[c]||(a.s[c]=[]);a.s[c].push(b);a.m&&delete a.m[c]}
function x(a,c){var b=[],d;for(d in c)0!=d&&b.push(new ha(d,c[d]));return new pa(a,b)};function z(){}z.prototype.ma=function(a){new a.Ga;throw Error("Unimplemented");};z.prototype.pa=function(a,c){if(11==a.da||10==a.da)return c instanceof n?c:this.ma(a.Aa.prototype.j(),c);if(14==a.da){if("string"===typeof c&&ta.test(c)){var b=Number(c);if(0<b)return b}return c}if(!a.va)return c;b=a.Aa;if(b===String){if("number"===typeof c)return String(c)}else if(b===Number&&"string"===typeof c&&("Infinity"===c||"-Infinity"===c||"NaN"===c||ta.test(c)))return Number(c);return c};var ta=/^-?[0-9]+$/;function ua(){}k(ua,z);ua.prototype.ma=function(a,c){var b=new a.Ga;b.za=this;b.s=c;b.m={};return b};function A(){}k(A,ua);A.prototype.Ka=!1;A.prototype.pa=function(a,c){return 8==a.da?!!c:z.prototype.pa.apply(this,arguments)};A.prototype.ma=function(a,c){var b=c;if(this.Ka){b=[];for(var d in c)b[parseInt(d,10)+1]=c[d]}return A.Ja.ma.call(this,a,b)};/*

 Protocol Buffer 2 Copyright 2008 Google Inc.
 All other code copyright its respective owners.
 Copyright (C) 2010 The Libphonenumber Authors

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
function B(){n.call(this)}k(B,n);var va=null;function C(){n.call(this)}k(C,n);var wa=null;C.prototype.Ea=function(){return q(this,6)};function D(){n.call(this)}k(D,n);var xa=null;D.prototype.Da=function(){return q(this,10)};D.prototype.fa=function(){return v(this,10)};D.prototype.ja=function(a){r(this,10,a)};
B.prototype.j=function(){var a=va;a||(va=a=x(B,{0:{name:"NumberFormat",wa:"i18n.phonenumbers.NumberFormat"},1:{name:"pattern",required:!0,g:9,type:String},2:{name:"format",required:!0,g:9,type:String},3:{name:"leading_digits_pattern",oa:!0,g:9,type:String},4:{name:"national_prefix_formatting_rule",g:9,type:String},6:{name:"national_prefix_optional_when_formatting",g:8,defaultValue:!1,type:Boolean},5:{name:"domestic_carrier_code_formatting_rule",g:9,type:String}}));return a};B.j=B.prototype.j;
C.prototype.j=function(){var a=wa;a||(wa=a=x(C,{0:{name:"PhoneNumberDesc",wa:"i18n.phonenumbers.PhoneNumberDesc"},2:{name:"national_number_pattern",g:9,type:String},9:{name:"possible_length",oa:!0,g:5,type:Number},10:{name:"possible_length_local_only",oa:!0,g:5,type:Number},6:{name:"example_number",g:9,type:String}}));return a};C.j=C.prototype.j;
D.prototype.j=function(){var a=xa;a||(xa=a=x(D,{0:{name:"PhoneMetadata",wa:"i18n.phonenumbers.PhoneMetadata"},1:{name:"general_desc",g:11,type:C},2:{name:"fixed_line",g:11,type:C},3:{name:"mobile",g:11,type:C},4:{name:"toll_free",g:11,type:C},5:{name:"premium_rate",g:11,type:C},6:{name:"shared_cost",g:11,type:C},7:{name:"personal_number",g:11,type:C},8:{name:"voip",g:11,type:C},21:{name:"pager",g:11,type:C},25:{name:"uan",g:11,type:C},27:{name:"emergency",g:11,type:C},28:{name:"voicemail",g:11,type:C},
29:{name:"short_code",g:11,type:C},30:{name:"standard_rate",g:11,type:C},31:{name:"carrier_specific",g:11,type:C},33:{name:"sms_services",g:11,type:C},24:{name:"no_international_dialling",g:11,type:C},9:{name:"id",required:!0,g:9,type:String},10:{name:"country_code",g:5,type:Number},11:{name:"international_prefix",g:9,type:String},17:{name:"preferred_international_prefix",g:9,type:String},12:{name:"national_prefix",g:9,type:String},13:{name:"preferred_extn_prefix",g:9,type:String},15:{name:"national_prefix_for_parsing",
g:9,type:String},16:{name:"national_prefix_transform_rule",g:9,type:String},18:{name:"same_mobile_and_fixed_line_pattern",g:8,defaultValue:!1,type:Boolean},19:{name:"number_format",oa:!0,g:11,type:B},20:{name:"intl_number_format",oa:!0,g:11,type:B},22:{name:"main_country_for_code",g:8,defaultValue:!1,type:Boolean},23:{name:"leading_digits",g:9,type:String},26:{name:"leading_zero_possible",g:8,defaultValue:!1,type:Boolean}}));return a};D.j=D.prototype.j;function E(){n.call(this)}k(E,n);var ya=null;E.prototype.Da=function(){return q(this,1)};E.prototype.fa=function(){return v(this,1)};E.prototype.ja=function(a){r(this,1,a)};E.prototype.getExtension=function(){return q(this,3)};var za={Pa:0,Oa:1,Na:5,Ma:10,La:20};
E.prototype.j=function(){var a=ya;a||(ya=a=x(E,{0:{name:"PhoneNumber",wa:"i18n.phonenumbers.PhoneNumber"},1:{name:"country_code",required:!0,g:5,type:Number},2:{name:"national_number",required:!0,g:4,type:Number},3:{name:"extension",g:9,type:String},4:{name:"italian_leading_zero",g:8,type:Boolean},8:{name:"number_of_leading_zeros",g:5,defaultValue:1,type:Number},5:{name:"raw_input",g:9,type:String},6:{name:"country_code_source",g:14,defaultValue:0,type:za},7:{name:"preferred_domestic_carrier_code",
g:9,type:String}}));return a};E.ctor=E;E.ctor.j=E.prototype.j;var F,G;function H(a){F=a.countryCodeToRegionCodeMap;G=a.countryToMetadata};/*

 Copyright (C) 2010 The Libphonenumber Authors.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
function I(){this.Ha={}}I.ya=void 0;I.Fa=function(){return I.ya?I.ya:I.ya=new I};
var Aa={0:"0",1:"1",2:"2",3:"3",4:"4",5:"5",6:"6",7:"7",8:"8",9:"9","\uff10":"0","\uff11":"1","\uff12":"2","\uff13":"3","\uff14":"4","\uff15":"5","\uff16":"6","\uff17":"7","\uff18":"8","\uff19":"9","\u0660":"0","\u0661":"1","\u0662":"2","\u0663":"3","\u0664":"4","\u0665":"5","\u0666":"6","\u0667":"7","\u0668":"8","\u0669":"9","\u06f0":"0","\u06f1":"1","\u06f2":"2","\u06f3":"3","\u06f4":"4","\u06f5":"5","\u06f6":"6","\u06f7":"7","\u06f8":"8","\u06f9":"9"},Ba={0:"0",1:"1",2:"2",3:"3",4:"4",5:"5",6:"6",
7:"7",8:"8",9:"9","+":"+","*":"*","#":"#"},Ca={0:"0",1:"1",2:"2",3:"3",4:"4",5:"5",6:"6",7:"7",8:"8",9:"9","\uff10":"0","\uff11":"1","\uff12":"2","\uff13":"3","\uff14":"4","\uff15":"5","\uff16":"6","\uff17":"7","\uff18":"8","\uff19":"9","\u0660":"0","\u0661":"1","\u0662":"2","\u0663":"3","\u0664":"4","\u0665":"5","\u0666":"6","\u0667":"7","\u0668":"8","\u0669":"9","\u06f0":"0","\u06f1":"1","\u06f2":"2","\u06f3":"3","\u06f4":"4","\u06f5":"5","\u06f6":"6","\u06f7":"7","\u06f8":"8","\u06f9":"9",A:"2",
B:"2",C:"2",D:"3",E:"3",F:"3",G:"4",H:"4",I:"4",J:"5",K:"5",L:"5",M:"6",N:"6",O:"6",P:"7",Q:"7",R:"7",S:"7",T:"8",U:"8",V:"8",W:"9",X:"9",Y:"9",Z:"9"},Da=RegExp("[+\uff0b]+"),J=RegExp("^[+\uff0b]+"),Ea=RegExp("([0-9\uff10-\uff19\u0660-\u0669\u06f0-\u06f9])"),Fa=RegExp("[+\uff0b0-9\uff10-\uff19\u0660-\u0669\u06f0-\u06f9]"),Ga=/[\\\/] *x/,Ha=RegExp("[^0-9\uff10-\uff19\u0660-\u0669\u06f0-\u06f9A-Za-z#]+$"),Ia=/(?:.*?[A-Za-z]){3}.*/;
function K(a){return"([0-9\uff10-\uff19\u0660-\u0669\u06f0-\u06f9]{1,"+a+"})"}
function Ja(){return";ext="+K("20")+"|[ \u00a0\\t,]*(?:e?xt(?:ensi(?:o\u0301?|\u00f3))?n?|\uff45?\uff58\uff54\uff4e?|\u0434\u043e\u0431|anexo)[:\\.\uff0e]?[ \u00a0\\t,-]*"+(K("20")+"#?|[ \u00a0\\t,]*(?:[x\uff58#\uff03~\uff5e]|int|\uff49\uff4e\uff54)[:\\.\uff0e]?[ \u00a0\\t,-]*")+(K("9")+"#?|[- ]+")+(K("6")+"#|[ \u00a0\\t]*(?:,{2}|;)[:\\.\uff0e]?[ \u00a0\\t,-]*")+(K("15")+"#?|[ \u00a0\\t]*(?:,)+[:\\.\uff0e]?[ \u00a0\\t,-]*")+(K("9")+"#?")}
var Ka=new RegExp("(?:"+Ja()+")$","i"),La=new RegExp("^[0-9\uff10-\uff19\u0660-\u0669\u06f0-\u06f9]{2}$|^[+\uff0b]*(?:[-x\u2010-\u2015\u2212\u30fc\uff0d-\uff0f \u00a0\u00ad\u200b\u2060\u3000()\uff08\uff09\uff3b\uff3d.\\[\\]/~\u2053\u223c\uff5e*]*[0-9\uff10-\uff19\u0660-\u0669\u06f0-\u06f9]){3,}[-x\u2010-\u2015\u2212\u30fc\uff0d-\uff0f \u00a0\u00ad\u200b\u2060\u3000()\uff08\uff09\uff3b\uff3d.\\[\\]/~\u2053\u223c\uff5e*A-Za-z0-9\uff10-\uff19\u0660-\u0669\u06f0-\u06f9]*(?:"+Ja()+")?$","i"),Ma=/(\$\d)/,
Na=/^\(?\$1\)?$/;function Oa(a){return 2>a.length?!1:L(La,a)}function Pa(a){return L(Ia,a)?M(a,Ca):M(a,Aa)}function Qa(a){var c=Pa(a.toString());a.clear();a.append(c)}function Ra(){return ca(Object.keys(G),function(a){return isNaN(a)})}function Sa(a){return null!=a&&(1!=w(a,9)||-1!=t(a,9)[0])}function M(a,c){for(var b=new l,d,e=a.length,f=0;f<e;++f)d=a.charAt(f),d=c[d.toUpperCase()],null!=d&&b.append(d);return b.toString()}function Ta(a){return 0==a.length||Na.test(a)}
function N(a){return null!=a&&isNaN(a)&&a.toUpperCase()in G}
I.prototype.format=function(a,c){if(0==q(a,2)&&p(a,5)){var b=v(a,5);if(0<b.length)return b}b=a.fa();var d=Ua(a);if(0==c)return Va(b,0,d,"");if(!(b in F))return d;var e=O(this,b,P(b));var f=p(a,3)&&0!=a.getExtension().length?3==c?";ext="+a.getExtension():p(e,13)?q(e,13)+v(a,3):" ext. "+v(a,3):"";a:{e=0==t(e,20).length||2==c?t(e,19):t(e,20);for(var g,h=e.length,m=0;m<h;++m){g=e[m];var y=w(g,3);if(0==y||0==d.search(q(g,3,y-1)))if(y=new RegExp(q(g,1)),L(y,d)){e=g;break a}}e=null}null!=e&&(h=e,e=v(h,2),
g=new RegExp(q(h,1)),v(h,5),h=v(h,4),d=2==c&&null!=h&&0<h.length?d.replace(g,e.replace(Ma,h)):d.replace(g,e),3==c&&(d=d.replace(RegExp("^[-x\u2010-\u2015\u2212\u30fc\uff0d-\uff0f \u00a0\u00ad\u200b\u2060\u3000()\uff08\uff09\uff3b\uff3d.\\[\\]/~\u2053\u223c\uff5e]+"),""),d=d.replace(RegExp("[-x\u2010-\u2015\u2212\u30fc\uff0d-\uff0f \u00a0\u00ad\u200b\u2060\u3000()\uff08\uff09\uff3b\uff3d.\\[\\]/~\u2053\u223c\uff5e]+","g"),"-")));return Va(b,c,d,f)};
function O(a,c,b){return"001"==b?Q(a,""+c):Q(a,b)}function Ua(a){if(!p(a,2))return"";var c=""+q(a,2);return p(a,4)&&q(a,4)&&0<v(a,8)?Array(v(a,8)+1).join("0")+c:c}function Va(a,c,b,d){switch(c){case 0:return"+"+a+b+d;case 1:return"+"+a+" "+b+d;case 3:return"tel:+"+a+"-"+b+d;default:return b+d}}I.prototype.Ea=function(){return Wa(this,void 0,0)};function Wa(a,c,b){if(!N(c))return null;b=R(Q(a,c),b);try{if(p(b,6))return a.parse(b.Ea(),c)}catch(d){}return null}
function R(a,c){switch(c){case 4:return q(a,5);case 3:return q(a,4);case 1:return q(a,3);case 0:case 2:return q(a,2);case 5:return q(a,6);case 6:return q(a,8);case 7:return q(a,7);case 8:return q(a,21);case 9:return q(a,25);case 10:return q(a,28);default:return q(a,1)}}function Q(a,c){if(null==c)return null;c=c.toUpperCase();var b=a.Ha[c];if(null==b){b=G[c];if(null==b)return null;b=(new A).ma(D.j(),b);a.Ha[c]=b}return b}
function S(a,c){var b=a.length;return 0<w(c,9)&&-1==ba(t(c,9),b)?!1:L(v(c,2),a)}function P(a){a=F[a];return null==a?"ZZ":a[0]}function Xa(a,c){var b=Q(a,c);if(null==b)throw Error("Invalid region code: "+c);return b.fa()}
function T(a,c,b,d){var e=R(b,d),f=0==w(e,9)?t(q(b,1),9):t(e,9);e=t(e,10);if(2==d)if(Sa(R(b,0)))a=R(b,1),Sa(a)&&(f=f.concat(0==w(a,9)?t(q(b,1),9):t(a,9)),da(f),0==e.length?e=t(a,10):(e=e.concat(t(a,10)),da(e)));else return T(a,c,b,1);if(-1==f[0])return 5;c=c.length;if(-1<ba(e,c))return 4;b=f[0];return b==c?0:b>c?2:f[f.length-1]<c?3:-1<ba(f,c,1)?0:5}
function Ya(a,c){var b=a.toString();if(0==b.length||"0"==b.charAt(0))return 0;for(var d,e=b.length,f=1;3>=f&&f<=e;++f)if(d=parseInt(b.substring(0,f),10),d in F)return c.append(b.substring(f)),d;return 0}
function Za(a,c,b,d,e){if(0==c.length)return 0;c=new l(c);var f;null!=b&&(f=q(b,11));null==f&&(f="NonMatch");var g=c.toString();if(0==g.length)f=20;else if(J.test(g))g=g.replace(J,""),c.clear(),c.append(Pa(g)),f=1;else{g=new RegExp(f);Qa(c);f=c.toString();if(0==f.search(g)){g=f.match(g)[0].length;var h=f.substring(g).match(Ea);h&&null!=h[1]&&0<h[1].length&&"0"==M(h[1],Aa)?f=!1:(c.clear(),c.append(f.substring(g)),f=!0)}else f=!1;f=f?5:20}if(20!=f){if(2>=c.l.length)throw Error("Phone number too short after IDD");
a=Ya(c,d);if(0!=a)return e.ja(a),a;throw Error("Invalid country calling code");}if(null!=b&&(f=b.fa(),g=""+f,h=c.toString(),0==h.lastIndexOf(g,0)&&(g=new l(h.substring(g.length)),h=q(b,1),h=new RegExp(v(h,2)),$a(g,b,null),g=g.toString(),!L(h,c.toString())&&L(h,g)||3==T(a,c.toString(),b,-1))))return d.append(g),e.ja(f),f;e.ja(0);return 0}
function $a(a,c,b){var d=a.toString(),e=d.length,f=q(c,15);if(0!=e&&null!=f&&0!=f.length){var g=new RegExp("^(?:"+f+")");if(e=g.exec(d)){f=new RegExp(v(q(c,1),2));var h=L(f,d),m=e.length-1;c=q(c,16);if(null==c||0==c.length||null==e[m]||0==e[m].length){if(!h||L(f,d.substring(e[0].length)))null!=b&&0<m&&null!=e[m]&&b.append(e[1]),a.set(d.substring(e[0].length))}else if(d=d.replace(g,c),!h||L(f,d))null!=b&&0<m&&b.append(e[1]),a.set(d)}}}
I.prototype.parse=function(a,c){if(null==a)throw Error("The string supplied did not seem to be a phone number");if(250<a.length)throw Error("The string supplied is too long to be a phone number");var b=new l,d=a.indexOf(";phone-context=");if(0<=d){var e=d+15;if("+"==a.charAt(e)){var f=a.indexOf(";",e);0<f?b.append(a.substring(e,f)):b.append(a.substring(e))}e=a.indexOf("tel:");b.append(a.substring(0<=e?e+4:0,d))}else d=b.append,e=a.search(Fa),0<=e?(e=a.substring(e),e=e.replace(Ha,""),f=e.search(Ga),
0<=f&&(e=e.substring(0,f))):e="",d.call(b,e);d=b.toString();e=d.indexOf(";isub=");0<e&&(b.clear(),b.append(d.substring(0,e)));if(!Oa(b.toString()))throw Error("The string supplied did not seem to be a phone number");d=b.toString();if(!(N(c)||null!=d&&0<d.length&&J.test(d)))throw Error("Invalid country calling code");d=new E;a:{e=b.toString();f=e.search(Ka);if(0<=f&&Oa(e.substring(0,f)))for(var g=e.match(Ka),h=g.length,m=1;m<h;++m)if(null!=g[m]&&0<g[m].length){b.clear();b.append(e.substring(0,f));
e=g[m];break a}e=""}0<e.length&&r(d,3,e);f=Q(this,c);e=new l;g=0;h=b.toString();try{g=Za(this,h,f,e,d)}catch(y){if("Invalid country calling code"==y.message&&J.test(h)){if(h=h.replace(J,""),g=Za(this,h,f,e,d),0==g)throw y;}else throw y;}0!=g?(b=P(g),b!=c&&(f=O(this,g,b))):(Qa(b),e.append(b.toString()),null!=c&&(g=f.fa(),d.ja(g)));if(2>e.l.length)throw Error("The string supplied is too short to be a phone number");null!=f&&(g=new l,b=new l(e.toString()),$a(b,f,g),f=T(this,b.toString(),f,-1),2!=f&&
4!=f&&5!=f&&(e=b));b=e.toString();e=b.length;if(2>e)throw Error("The string supplied is too short to be a phone number");if(17<e)throw Error("The string supplied is too long to be a phone number");if(1<b.length&&"0"==b.charAt(0)){r(d,4,!0);for(e=1;e<b.length-1&&"0"==b.charAt(e);)e++;1!=e&&r(d,8,e)}r(d,2,parseInt(b,10));return d};function L(a,c){var b="string"==typeof a?c.match("^(?:"+a+")$"):c.match(a);return b&&b[0].length==c.length?!0:!1};function ab(a){this.Ca="\u2008";this.sa=new RegExp(this.Ca);this.ta="";this.ea=new l;this.ka="";this.aa=new l;this.ga=new l;this.ba=!0;this.na=this.ha=this.xa=!1;this.Ba=I.Fa();this.ia=0;this.i=new l;this.ra=!1;this.v="";this.h=new l;this.o=[];this.ua=a;this.Ia=this.u=bb(this,this.ua)}var cb=new D;r(cb,11,"NA");
var db=RegExp("^[-x\u2010-\u2015\u2212\u30fc\uff0d-\uff0f \u00a0\u00ad\u200b\u2060\u3000()\uff08\uff09\uff3b\uff3d.\\[\\]/~\u2053\u223c\uff5e]*(\\$\\d[-x\u2010-\u2015\u2212\u30fc\uff0d-\uff0f \u00a0\u00ad\u200b\u2060\u3000()\uff08\uff09\uff3b\uff3d.\\[\\]/~\u2053\u223c\uff5e]*)+$"),eb=/[- ]/;function bb(a,c){var b=a.Ba;b=N(c)?Xa(b,c):0;b=Q(a.Ba,P(b));return null!=b?b:cb}
function fb(a){for(var c=a.o.length,b=0;b<c;++b){var d=a.o[b],e=v(d,1);if(a.ka==e)return!1;var f=a;var g=d,h=v(g,1);f.ea.clear();var m=f;g=v(g,2);var y="999999999999999".match(h)[0];y.length<m.h.l.length?m="":(h=y.replace(new RegExp(h,"g"),g),m=h=h.replace(RegExp("9","g"),m.Ca));0<m.length?(f.ea.append(m),f=!0):f=!1;if(f)return a.ka=e,a.ra=eb.test(q(d,4)),a.ia=0,!0}return a.ba=!1}
function gb(a,c){for(var b=[],d=c.length-3,e=a.o.length,f=0;f<e;++f){var g=a.o[f];0==w(g,3)?b.push(a.o[f]):(g=q(g,3,Math.min(d,w(g,3)-1)),0==c.search(g)&&b.push(a.o[f]))}a.o=b}ab.prototype.clear=function(){this.ta="";this.aa.clear();this.ga.clear();this.ea.clear();this.ia=0;this.ka="";this.i.clear();this.v="";this.h.clear();this.ba=!0;this.na=this.ha=this.xa=!1;this.o=[];this.ra=!1;this.u!=this.Ia&&(this.u=bb(this,this.ua))};
function hb(a,c){a.aa.append(c);var b=c;if(Ea.test(b)||1==a.aa.l.length&&Da.test(b)){b=c;if("+"==b){var d=b;a.ga.append(b)}else d=Aa[b],a.ga.append(d),a.h.append(d);c=d}else a.ba=!1,a.xa=!0;if(!a.ba){if(!a.xa)if(ib(a)){if(jb(a))return kb(a)}else if(0<a.v.length&&(b=a.h.toString(),a.h.clear(),a.h.append(a.v),a.h.append(b),b=a.i.toString(),d=b.lastIndexOf(a.v),a.i.clear(),a.i.append(b.substring(0,d))),a.v!=lb(a))return a.i.append(" "),kb(a);return a.aa.toString()}switch(a.ga.l.length){case 0:case 1:case 2:return a.aa.toString();
case 3:if(ib(a))a.na=!0;else return a.v=lb(a),mb(a);default:if(a.na)return jb(a)&&(a.na=!1),a.i.toString()+a.h.toString();if(0<a.o.length){b=nb(a,c);d=ob(a);if(0<d.length)return d;gb(a,a.h.toString());return fb(a)?pb(a):a.ba?U(a,b):a.aa.toString()}return mb(a)}}function kb(a){a.ba=!0;a.na=!1;a.o=[];a.ia=0;a.ea.clear();a.ka="";return mb(a)}
function ob(a){for(var c=a.h.toString(),b=a.o.length,d=0;d<b;++d){var e=a.o[d],f=v(e,1);if((new RegExp("^(?:"+f+")$")).test(c)&&(a.ra=eb.test(q(e,4)),e=c.replace(new RegExp(f,"g"),q(e,2)),e=U(a,e),M(e,Ba)==a.ga))return e}return""}function U(a,c){var b=a.i.l.length;return a.ra&&0<b&&" "!=a.i.toString().charAt(b-1)?a.i+" "+c:a.i+c}
function mb(a){var c=a.h.toString();if(3<=c.length){for(var b=a.ha&&0==a.v.length&&0<w(a.u,20)?t(a.u,20):t(a.u,19),d=b.length,e=0;e<d;++e){var f=b[e];0<a.v.length&&Ta(v(f,4))&&!q(f,6)&&!p(f,5)||(0!=a.v.length||a.ha||Ta(v(f,4))||q(f,6))&&db.test(v(f,2))&&a.o.push(f)}gb(a,c);c=ob(a);return 0<c.length?c:fb(a)?pb(a):a.aa.toString()}return U(a,c)}
function pb(a){var c=a.h.toString(),b=c.length;if(0<b){for(var d="",e=0;e<b;e++)d=nb(a,c.charAt(e));return a.ba?U(a,d):a.aa.toString()}return a.i.toString()}
function lb(a){var c=a.h.toString(),b=0;if(1!=a.u.Da())var d=!1;else d=a.h.toString(),d="1"==d.charAt(0)&&"0"!=d.charAt(1)&&"1"!=d.charAt(1);d?(b=1,a.i.append("1").append(" "),a.ha=!0):p(a.u,15)&&(d=new RegExp("^(?:"+q(a.u,15)+")"),d=c.match(d),null!=d&&null!=d[0]&&0<d[0].length&&(a.ha=!0,b=d[0].length,a.i.append(c.substring(0,b))));a.h.clear();a.h.append(c.substring(b));return c.substring(0,b)}
function ib(a){var c=a.ga.toString(),b=new RegExp("^(?:\\+|"+q(a.u,11)+")");b=c.match(b);return null!=b&&null!=b[0]&&0<b[0].length?(a.ha=!0,b=b[0].length,a.h.clear(),a.h.append(c.substring(b)),a.i.clear(),a.i.append(c.substring(0,b)),"+"!=c.charAt(0)&&a.i.append(" "),!0):!1}function jb(a){if(0==a.h.l.length)return!1;var c=new l,b=Ya(a.h,c);if(0==b)return!1;a.h.clear();a.h.append(c.toString());c=P(b);"001"==c?a.u=Q(a.Ba,""+b):c!=a.ua&&(a.u=bb(a,c));a.i.append(""+b).append(" ");a.v="";return!0}
function nb(a,c){var b=a.ea.toString();if(0<=b.substring(a.ia).search(a.sa)){var d=b.search(a.sa);b=b.replace(a.sa,c);a.ea.clear();a.ea.append(b);a.ia=d;return b.substring(0,a.ia+1)}1==a.o.length&&(a.ba=!1);a.ka="";return a.aa.toString()};var V=I.Fa(),qb={e164:0,international:1,national:2,rfc3966:3},rb={FIXED_LINE:0,MOBILE:1,FIXED_LINE_OR_MOBILE:2,TOLL_FREE:3,PREMIUM_RATE:4,SHARED_COST:5,VOIP:6,PERSONAL_NUMBER:7,PAGER:8,UAN:9,VOICEMAIL:10},sb={"Invalid country calling code":"PHONE_INVALID_COUNTRY_CODE","The string supplied is too short to be a phone number":"PHONE_NUMBER_TOO_SHORT","The string supplied is too long to be a phone number":"PHONE_NUMBER_TOO_LONG","The string supplied did not seem to be a phone number":"PHONE_NOT_A_NUMBER",
"Phone number too short after IDD":"PHONE_TOO_SHORT_AFTER_IDD"};function tb(a){if(!ub(a))throw Error("Invalid metadata");var c=a.regionCodes;if(!c||!Array.isArray(c)||!c.length)throw Error("Invalid metadata");if(!ub(a.countryCodeToRegionCodeMap)||!ub(a.countryToMetadata))throw Error("Invalid metadata");}function ub(a){return null!==a&&"[object Object]"===""+a&&a.constructor===Object}function W(a,c){if(-1===c.regionCodes.indexOf(a))throw Error("Metadata not loaded for region: "+a);}
function vb(a){if(null===a)return null;var c={countryCode:a.s[1].toString(),nationalNumber:a.s[2].toString()};if(p(a,4))for(var b=v(a,8),d=0;d<b;d++)c.nationalNumber="0"+c.nationalNumber;void 0!==a.s[3]&&(c.extension=a.s[3]);return c}
function wb(a){var c=new E,b=!1;c.ja(Number(a.countryCode));var d=a.nationalNumber;if("string"===typeof d){for(var e=0;"0"===d.charAt(e);)b=!0,e++;b&&(r(c,4,!0),r(c,8,e));d=Number(d)}r(c,2,d);void 0!==a.extension&&null!==a.extension&&(a=a.extension.toString(),r(c,3,a));return c}
function xb(a){tb(a);return{getSupportedRegions:function(){H(a);return Ra()},getCountryCodeForRegion:function(c){H(a);W(c,a);return N(c)?Xa(V,c):0},countryCodeToRegionCodeMap:function(){H(a);return F},formatPhoneNumber:function(c,b){H(a);try{var d=wb(c)}catch(f){throw Error("Phone object conversion failed: "+f.message);}b=b||{};var e=qb[b.style];if(void 0===e)throw Error("Invalid style property: "+b.style);return V.format(d,e).toString()},validatePhoneNumber:function(c,b){H(a);W(b,a);try{var d=wb(c)}catch(h){throw Error("Phone object conversion failed: "+
h.message);}var e=d,f=e.fa();var g=O(V,f,b);null==g||"001"!=b&&f!=Xa(V,b)?g=!1:(e=Ua(e),g=-1!=(S(e,q(g,1))?S(e,q(g,5))?4:S(e,q(g,4))?3:S(e,q(g,6))?5:S(e,q(g,8))?6:S(e,q(g,7))?7:S(e,q(g,21))?8:S(e,q(g,25))?9:S(e,q(g,28))?10:S(e,q(g,2))?q(g,18)||S(e,q(g,3))?2:0:!q(g,18)&&S(e,q(g,3))?1:-1:-1));if(g)return!0;g=d;d=Ua(g);g=g.fa();g in F?(g=O(V,g,P(g)),d=T(V,d,g,-1)):d=1;switch(d){case 1:d="PHONE_INVALID_COUNTRY_CODE";break;case 2:d="PHONE_NUMBER_TOO_SHORT";break;case 3:d="PHONE_NUMBER_TOO_LONG";break;
case 5:d="PHONE_NUMBER_INVALID_LENGTH";break;default:d="PHONE_INVALID_FOR_REGION"}return Error(d)},parsePhoneNumber:function(c,b){H(a);W(b,a);try{var d=V.parse(c,b)}catch(e){return Error(sb[e.message])}return vb(d)},getExampleNumberForType:function(c,b){H(a);W(b,a);var d=rb[c];void 0===d&&(d=-1);return vb(Wa(V,b,d))},getAsYouTypeFormatter:function(c){H(a);W(c,a);var b=new ab(c);return{inputDigit:function(d){b.ta=hb(b,d);return b.ta},clear:function(){return b.clear()}}}}}
var X=["createPhoneHandler"],Y=aa;X[0]in Y||"undefined"==typeof Y.execScript||Y.execScript("var "+X[0]);for(var Z;X.length&&(Z=X.shift());)X.length||void 0===xb?Y=Y[Z]&&Y[Z]!==Object.prototype[Z]?Y[Z]:Y[Z]={}:Y[Z]=xb;
