/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var aa;if(void 0!==this)aa=this;else if("undefined"!=typeof global)aa=global;else{if("undefined"==typeof self)throw new Error("Can't find global scope");aa=self};function k(a,b){function c(){}c.prototype=b.prototype;a.Fa=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Ma=function(d,e,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[e].apply(d,g)}};function l(a,b){null!=a&&this.append.apply(this,arguments)}l.prototype.g="";l.prototype.set=function(a){this.g=""+a};l.prototype.append=function(a,b,c){this.g+=String(a);if(null!=b)for(var d=1;d<arguments.length;d++)this.g+=arguments[d];return this};l.prototype.clear=function(){this.g=""};l.prototype.toString=function(){return this.g};var ba=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},ca=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=[],e=0,f="string"===typeof a?a.split(""):a,g=0;g<c;g++)if(g in f){var h=f[g];b.call(void 0,
h,g,a)&&(d[e++]=h)}return d};function da(a,b){a.sort(b||ea)}function ea(a,b){return a>b?1:a<b?-1:0};function fa(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};function ha(a,b){this.o=a;this.ma=!!b.ka;this.$=b.a;this.wa=b.type;this.ra=!1;switch(this.$){case ia:case ja:case ka:case la:case ma:case na:case oa:this.ra=!0}this.ha=b.defaultValue}var oa=1,na=2,ia=3,ja=4,ka=6,la=16,ma=18;function pa(a,b){this.Ca=a;this.v={};for(var c=0;c<b.length;c++){var d=b[c];this.v[d.o]=d}}function qa(a){a=fa(a.v);da(a,function(b,c){return b.o-c.o});return a};function n(){this.j={};this.v=this.f().v;this.h=this.va=null}n.prototype.has=function(a){return p(this,a.o)};n.prototype.get=function(a,b){return q(this,a.o,b)};n.prototype.set=function(a,b){r(this,a.o,b)};n.prototype.add=function(a,b){ra(this,a.o,b)};n.prototype.clear=function(a){a=a.o;delete this.j[a];this.h&&delete this.h[a]};
function sa(a,b){for(var c=qa(a.f()),d=0;d<c.length;d++){var e=c[d],f=e.o;if(p(b,f)){a.h&&delete a.h[e.o];var g=11==e.$||10==e.$;if(e.ma){e=t(b,f);for(var h=0;h<e.length;h++)ra(a,f,g?e[h].clone():e[h])}else e=u(b,f),g?(g=u(a,f))?sa(g,e):r(a,f,e.clone()):r(a,f,e)}}}n.prototype.clone=function(){var a=new this.constructor;a!=this&&(a.j={},a.h&&(a.h={}),sa(a,this));return a};function p(a,b){return null!=a.j[b]}
function u(a,b){var c=a.j[b];if(null==c)return null;if(a.va){if(!(b in a.h)){var d=a.va,e=a.v[b];if(null!=c)if(e.ma){for(var f=[],g=0;g<c.length;g++)f[g]=d.la(e,c[g]);c=f}else c=d.la(e,c);return a.h[b]=c}return a.h[b]}return c}function q(a,b,c){var d=u(a,b);return a.v[b].ma?d[c||0]:d}function v(a,b){if(p(a,b))var c=q(a,b,void 0);else a:{c=a.v[b];if(void 0===c.ha){var d=c.wa;if(d===Boolean)c.ha=!1;else if(d===Number)c.ha=0;else if(d===String)c.ha=c.ra?"0":"";else{c=new d;break a}}c=c.ha}return c}
function t(a,b){return u(a,b)||[]}function w(a,b){return a.v[b].ma?p(a,b)?a.j[b].length:0:p(a,b)?1:0}function r(a,b,c){a.j[b]=c;a.h&&(a.h[b]=c)}function ra(a,b,c){a.j[b]||(a.j[b]=[]);a.j[b].push(c);a.h&&delete a.h[b]}function x(a,b){var c=[],d;for(d in b)0!=d&&c.push(new ha(d,b[d]));return new pa(a,c)};function z(){}z.prototype.ia=function(a){new a.Ca;throw Error("Unimplemented");};z.prototype.la=function(a,b){if(11==a.$||10==a.$)return b instanceof n?b:this.ia(a.wa.prototype.f(),b);if(14==a.$){if("string"===typeof b&&ta.test(b)){var c=Number(b);if(0<c)return c}return b}if(!a.ra)return b;c=a.wa;if(c===String){if("number"===typeof b)return String(b)}else if(c===Number&&"string"===typeof b&&("Infinity"===b||"-Infinity"===b||"NaN"===b||ta.test(b)))return Number(b);return b};var ta=/^-?[0-9]+$/;function ua(){}k(ua,z);ua.prototype.ia=function(a,b){var c=new a.Ca;c.va=this;c.j=b;c.h={};return c};function A(){}k(A,ua);A.prototype.Ga=!1;A.prototype.la=function(a,b){return 8==a.$?!!b:z.prototype.la.apply(this,arguments)};A.prototype.ia=function(a,b){var c=b;if(this.Ga){c=[];for(var d in b)c[parseInt(d,10)+1]=b[d]}return A.Fa.ia.call(this,a,c)};/*

 Protocol Buffer 2 Copyright 2008 Google Inc.
 All other code copyright its respective owners.
 Copyright (C) 2010 The Libphonenumber Authors

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
function B(){n.call(this)}k(B,n);var va=null;function C(){n.call(this)}k(C,n);var wa=null;C.prototype.Aa=function(){return q(this,6)};function D(){n.call(this)}k(D,n);var xa=null;D.prototype.za=function(){return q(this,10)};D.prototype.ba=function(){return v(this,10)};D.prototype.fa=function(a){r(this,10,a)};
B.prototype.f=function(){var a=va;a||(va=a=x(B,{0:{name:"NumberFormat",sa:"i18n.phonenumbers.NumberFormat"},1:{name:"pattern",required:!0,a:9,type:String},2:{name:"format",required:!0,a:9,type:String},3:{name:"leading_digits_pattern",ka:!0,a:9,type:String},4:{name:"national_prefix_formatting_rule",a:9,type:String},6:{name:"national_prefix_optional_when_formatting",a:8,defaultValue:!1,type:Boolean},5:{name:"domestic_carrier_code_formatting_rule",a:9,type:String}}));return a};B.f=B.prototype.f;
C.prototype.f=function(){var a=wa;a||(wa=a=x(C,{0:{name:"PhoneNumberDesc",sa:"i18n.phonenumbers.PhoneNumberDesc"},2:{name:"national_number_pattern",a:9,type:String},9:{name:"possible_length",ka:!0,a:5,type:Number},10:{name:"possible_length_local_only",ka:!0,a:5,type:Number},6:{name:"example_number",a:9,type:String}}));return a};C.f=C.prototype.f;
D.prototype.f=function(){var a=xa;a||(xa=a=x(D,{0:{name:"PhoneMetadata",sa:"i18n.phonenumbers.PhoneMetadata"},1:{name:"general_desc",a:11,type:C},2:{name:"fixed_line",a:11,type:C},3:{name:"mobile",a:11,type:C},4:{name:"toll_free",a:11,type:C},5:{name:"premium_rate",a:11,type:C},6:{name:"shared_cost",a:11,type:C},7:{name:"personal_number",a:11,type:C},8:{name:"voip",a:11,type:C},21:{name:"pager",a:11,type:C},25:{name:"uan",a:11,type:C},27:{name:"emergency",a:11,type:C},28:{name:"voicemail",a:11,type:C},
29:{name:"short_code",a:11,type:C},30:{name:"standard_rate",a:11,type:C},31:{name:"carrier_specific",a:11,type:C},33:{name:"sms_services",a:11,type:C},24:{name:"no_international_dialling",a:11,type:C},9:{name:"id",required:!0,a:9,type:String},10:{name:"country_code",a:5,type:Number},11:{name:"international_prefix",a:9,type:String},17:{name:"preferred_international_prefix",a:9,type:String},12:{name:"national_prefix",a:9,type:String},13:{name:"preferred_extn_prefix",a:9,type:String},15:{name:"national_prefix_for_parsing",
a:9,type:String},16:{name:"national_prefix_transform_rule",a:9,type:String},18:{name:"same_mobile_and_fixed_line_pattern",a:8,defaultValue:!1,type:Boolean},19:{name:"number_format",ka:!0,a:11,type:B},20:{name:"intl_number_format",ka:!0,a:11,type:B},22:{name:"main_country_for_code",a:8,defaultValue:!1,type:Boolean},23:{name:"leading_digits",a:9,type:String},26:{name:"leading_zero_possible",a:8,defaultValue:!1,type:Boolean}}));return a};D.f=D.prototype.f;function E(){n.call(this)}k(E,n);var ya=null;E.prototype.za=function(){return q(this,1)};E.prototype.ba=function(){return v(this,1)};E.prototype.fa=function(a){r(this,1,a)};E.prototype.getExtension=function(){return q(this,3)};var za={La:0,Ka:1,Ja:5,Ia:10,Ha:20};
E.prototype.f=function(){var a=ya;a||(ya=a=x(E,{0:{name:"PhoneNumber",sa:"i18n.phonenumbers.PhoneNumber"},1:{name:"country_code",required:!0,a:5,type:Number},2:{name:"national_number",required:!0,a:4,type:Number},3:{name:"extension",a:9,type:String},4:{name:"italian_leading_zero",a:8,type:Boolean},8:{name:"number_of_leading_zeros",a:5,defaultValue:1,type:Number},5:{name:"raw_input",a:9,type:String},6:{name:"country_code_source",a:14,defaultValue:0,type:za},7:{name:"preferred_domestic_carrier_code",
a:9,type:String}}));return a};E.ctor=E;E.ctor.f=E.prototype.f;var F,G;function H(a){F=a.countryCodeToRegionCodeMap;G=a.countryToMetadata};/*

 Copyright (C) 2010 The Libphonenumber Authors.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
function I(){this.Da={}}I.ua=void 0;I.Ba=function(){return I.ua?I.ua:I.ua=new I};
var Aa={0:"0",1:"1",2:"2",3:"3",4:"4",5:"5",6:"6",7:"7",8:"8",9:"9","\uff10":"0","\uff11":"1","\uff12":"2","\uff13":"3","\uff14":"4","\uff15":"5","\uff16":"6","\uff17":"7","\uff18":"8","\uff19":"9","\u0660":"0","\u0661":"1","\u0662":"2","\u0663":"3","\u0664":"4","\u0665":"5","\u0666":"6","\u0667":"7","\u0668":"8","\u0669":"9","\u06f0":"0","\u06f1":"1","\u06f2":"2","\u06f3":"3","\u06f4":"4","\u06f5":"5","\u06f6":"6","\u06f7":"7","\u06f8":"8","\u06f9":"9"},Ba={0:"0",1:"1",2:"2",3:"3",4:"4",5:"5",6:"6",
7:"7",8:"8",9:"9","+":"+","*":"*","#":"#"},Ca={0:"0",1:"1",2:"2",3:"3",4:"4",5:"5",6:"6",7:"7",8:"8",9:"9","\uff10":"0","\uff11":"1","\uff12":"2","\uff13":"3","\uff14":"4","\uff15":"5","\uff16":"6","\uff17":"7","\uff18":"8","\uff19":"9","\u0660":"0","\u0661":"1","\u0662":"2","\u0663":"3","\u0664":"4","\u0665":"5","\u0666":"6","\u0667":"7","\u0668":"8","\u0669":"9","\u06f0":"0","\u06f1":"1","\u06f2":"2","\u06f3":"3","\u06f4":"4","\u06f5":"5","\u06f6":"6","\u06f7":"7","\u06f8":"8","\u06f9":"9",A:"2",
B:"2",C:"2",D:"3",E:"3",F:"3",G:"4",H:"4",I:"4",J:"5",K:"5",L:"5",M:"6",N:"6",O:"6",P:"7",Q:"7",R:"7",S:"7",T:"8",U:"8",V:"8",W:"9",X:"9",Y:"9",Z:"9"},Da=RegExp("[+\uff0b]+"),J=RegExp("^[+\uff0b]+"),Ea=RegExp("([0-9\uff10-\uff19\u0660-\u0669\u06f0-\u06f9])"),Fa=RegExp("[+\uff0b0-9\uff10-\uff19\u0660-\u0669\u06f0-\u06f9]"),Ga=/[\\\/] *x/,Ha=RegExp("[^0-9\uff10-\uff19\u0660-\u0669\u06f0-\u06f9A-Za-z#]+$"),Ia=/(?:.*?[A-Za-z]){3}.*/;
function K(a){return"([0-9\uff10-\uff19\u0660-\u0669\u06f0-\u06f9]{1,"+a+"})"}
function Ja(){return";ext="+K("20")+"|[ \u00a0\\t,]*(?:e?xt(?:ensi(?:o\u0301?|\u00f3))?n?|\uff45?\uff58\uff54\uff4e?|\u0434\u043e\u0431|anexo)[:\\.\uff0e]?[ \u00a0\\t,-]*"+(K("20")+"#?|[ \u00a0\\t,]*(?:[x\uff58#\uff03~\uff5e]|int|\uff49\uff4e\uff54)[:\\.\uff0e]?[ \u00a0\\t,-]*")+(K("9")+"#?|[- ]+")+(K("6")+"#|[ \u00a0\\t]*(?:,{2}|;)[:\\.\uff0e]?[ \u00a0\\t,-]*")+(K("15")+"#?|[ \u00a0\\t]*(?:,)+[:\\.\uff0e]?[ \u00a0\\t,-]*")+(K("9")+"#?")}
var Ka=new RegExp("(?:"+Ja()+")$","i"),La=new RegExp("^[0-9\uff10-\uff19\u0660-\u0669\u06f0-\u06f9]{2}$|^[+\uff0b]*(?:[-x\u2010-\u2015\u2212\u30fc\uff0d-\uff0f \u00a0\u00ad\u200b\u2060\u3000()\uff08\uff09\uff3b\uff3d.\\[\\]/~\u2053\u223c\uff5e*]*[0-9\uff10-\uff19\u0660-\u0669\u06f0-\u06f9]){3,}[-x\u2010-\u2015\u2212\u30fc\uff0d-\uff0f \u00a0\u00ad\u200b\u2060\u3000()\uff08\uff09\uff3b\uff3d.\\[\\]/~\u2053\u223c\uff5e*A-Za-z0-9\uff10-\uff19\u0660-\u0669\u06f0-\u06f9]*(?:"+Ja()+")?$","i"),Ma=/(\$\d)/,
Na=/^\(?\$1\)?$/;function Oa(a){var b=a.search(Fa);0<=b?(a=a.substring(b),a=a.replace(Ha,""),b=a.search(Ga),0<=b&&(a=a.substring(0,b))):a="";return a}function Pa(a){return 2>a.length?!1:L(La,a)}function Qa(a){return L(Ia,a)?M(a,Ca):M(a,Aa)}function Ra(a){var b=Qa(a.toString());a.clear();a.append(b)}function Sa(){return ca(Object.keys(G),function(a){return isNaN(a)})}function Ta(a){return null!=a&&(1!=w(a,9)||-1!=t(a,9)[0])}
function M(a,b){for(var c=new l,d,e=a.length,f=0;f<e;++f)d=a.charAt(f),d=b[d.toUpperCase()],null!=d&&c.append(d);return c.toString()}function Ua(a){return 0==a.length||Na.test(a)}function N(a){return null!=a&&isNaN(a)&&a.toUpperCase()in G}
I.prototype.format=function(a,b){if(0==q(a,2)&&p(a,5)){var c=v(a,5);if(0<c.length)return c}c=a.ba();var d=Va(a);if(0==b)return Wa(c,0,d,"");if(!(c in F))return d;var e=O(this,c,P(c));var f=p(a,3)&&0!=a.getExtension().length?3==b?";ext="+a.getExtension():p(e,13)?q(e,13)+v(a,3):" ext. "+v(a,3):"";a:{e=0==t(e,20).length||2==b?t(e,19):t(e,20);for(var g,h=e.length,m=0;m<h;++m){g=e[m];var y=w(g,3);if(0==y||0==d.search(q(g,3,y-1)))if(y=new RegExp(q(g,1)),L(y,d)){e=g;break a}}e=null}null!=e&&(h=e,e=v(h,2),
g=new RegExp(q(h,1)),v(h,5),h=v(h,4),d=2==b&&null!=h&&0<h.length?d.replace(g,e.replace(Ma,h)):d.replace(g,e),3==b&&(d=d.replace(RegExp("^[-x\u2010-\u2015\u2212\u30fc\uff0d-\uff0f \u00a0\u00ad\u200b\u2060\u3000()\uff08\uff09\uff3b\uff3d.\\[\\]/~\u2053\u223c\uff5e]+"),""),d=d.replace(RegExp("[-x\u2010-\u2015\u2212\u30fc\uff0d-\uff0f \u00a0\u00ad\u200b\u2060\u3000()\uff08\uff09\uff3b\uff3d.\\[\\]/~\u2053\u223c\uff5e]+","g"),"-")));return Wa(c,b,d,f)};
function O(a,b,c){return"001"==c?Q(a,""+b):Q(a,c)}function Va(a){if(!p(a,2))return"";var b=""+q(a,2);return p(a,4)&&q(a,4)&&0<v(a,8)?Array(v(a,8)+1).join("0")+b:b}function Wa(a,b,c,d){switch(b){case 0:return"+"+a+c+d;case 1:return"+"+a+" "+c+d;case 3:return"tel:+"+a+"-"+c+d;default:return c+d}}I.prototype.Aa=function(){return Xa(this,void 0,0)};function Xa(a,b,c){if(!N(b))return null;c=R(Q(a,b),c);try{if(p(c,6))return a.parse(c.Aa(),b)}catch(d){}return null}
function R(a,b){switch(b){case 4:return q(a,5);case 3:return q(a,4);case 1:return q(a,3);case 0:case 2:return q(a,2);case 5:return q(a,6);case 6:return q(a,8);case 7:return q(a,7);case 8:return q(a,21);case 9:return q(a,25);case 10:return q(a,28);default:return q(a,1)}}function Q(a,b){if(null==b)return null;b=b.toUpperCase();var c=a.Da[b];if(null==c){c=G[b];if(null==c)return null;c=(new A).ia(D.f(),c);a.Da[b]=c}return c}
function S(a,b){var c=a.length;return 0<w(b,9)&&-1==ba(t(b,9),c)?!1:L(v(b,2),a)}function P(a){a=F[a];return null==a?"ZZ":a[0]}function Ya(a,b){var c=Q(a,b);if(null==c)throw Error("Invalid region code: "+b);return c.ba()}
function T(a,b,c,d){var e=R(c,d),f=0==w(e,9)?t(q(c,1),9):t(e,9);e=t(e,10);if(2==d)if(Ta(R(c,0)))a=R(c,1),Ta(a)&&(f=f.concat(0==w(a,9)?t(q(c,1),9):t(a,9)),da(f),0==e.length?e=t(a,10):(e=e.concat(t(a,10)),da(e)));else return T(a,b,c,1);if(-1==f[0])return 5;b=b.length;if(-1<ba(e,b))return 4;c=f[0];return c==b?0:c>b?2:f[f.length-1]<b?3:-1<ba(f,b,1)?0:5}
function Za(a,b){var c=a.toString();if(0==c.length||"0"==c.charAt(0))return 0;for(var d,e=c.length,f=1;3>=f&&f<=e;++f)if(d=parseInt(c.substring(0,f),10),d in F)return b.append(c.substring(f)),d;return 0}
function $a(a,b,c,d,e){if(0==b.length)return 0;b=new l(b);var f;null!=c&&(f=q(c,11));null==f&&(f="NonMatch");var g=b.toString();if(0==g.length)f=20;else if(J.test(g))g=g.replace(J,""),b.clear(),b.append(Qa(g)),f=1;else{g=new RegExp(f);Ra(b);f=b.toString();if(0==f.search(g)){g=f.match(g)[0].length;var h=f.substring(g).match(Ea);h&&null!=h[1]&&0<h[1].length&&"0"==M(h[1],Aa)?f=!1:(b.clear(),b.append(f.substring(g)),f=!0)}else f=!1;f=f?5:20}if(20!=f){if(2>=b.g.length)throw Error("Phone number too short after IDD");
a=Za(b,d);if(0!=a)return e.fa(a),a;throw Error("Invalid country calling code");}if(null!=c&&(f=c.ba(),g=""+f,h=b.toString(),0==h.lastIndexOf(g,0)&&(g=new l(h.substring(g.length)),h=q(c,1),h=new RegExp(v(h,2)),ab(g,c,null),g=g.toString(),!L(h,b.toString())&&L(h,g)||3==T(a,b.toString(),c,-1))))return d.append(g),e.fa(f),f;e.fa(0);return 0}
function ab(a,b,c){var d=a.toString(),e=d.length,f=q(b,15);if(0!=e&&null!=f&&0!=f.length){var g=new RegExp("^(?:"+f+")");if(e=g.exec(d)){f=new RegExp(v(q(b,1),2));var h=L(f,d),m=e.length-1;b=q(b,16);if(null==b||0==b.length||null==e[m]||0==e[m].length){if(!h||L(f,d.substring(e[0].length)))null!=c&&0<m&&null!=e[m]&&c.append(e[1]),a.set(d.substring(e[0].length))}else if(d=d.replace(g,b),!h||L(f,d))null!=c&&0<m&&c.append(e[1]),a.set(d)}}}
I.prototype.parse=function(a,b){if(null==a)throw Error("The string supplied did not seem to be a phone number");if(250<a.length)throw Error("The string supplied is too long to be a phone number");var c=new l,d=a.indexOf(";phone-context=");if(0<=d){var e=d+15;if("+"==a.charAt(e)){var f=a.indexOf(";",e);0<f?c.append(a.substring(e,f)):c.append(a.substring(e))}e=a.indexOf("tel:");c.append(a.substring(0<=e?e+4:0,d))}else c.append(Oa(a));d=c.toString();e=d.indexOf(";isub=");0<e&&(c.clear(),c.append(d.substring(0,
e)));if(!Pa(c.toString()))throw Error("The string supplied did not seem to be a phone number");d=c.toString();if(!(N(b)||null!=d&&0<d.length&&J.test(d)))throw Error("Invalid country calling code");d=new E;a:{e=c.toString();f=e.search(Ka);if(0<=f&&Pa(e.substring(0,f)))for(var g=e.match(Ka),h=g.length,m=1;m<h;++m)if(null!=g[m]&&0<g[m].length){c.clear();c.append(e.substring(0,f));e=g[m];break a}e=""}0<e.length&&r(d,3,e);f=Q(this,b);e=new l;g=0;h=c.toString();try{g=$a(this,h,f,e,d)}catch(y){if("Invalid country calling code"==
y.message&&J.test(h)){if(h=h.replace(J,""),g=$a(this,h,f,e,d),0==g)throw y;}else throw y;}0!=g?(c=P(g),c!=b&&(f=O(this,g,c))):(Ra(c),e.append(c.toString()),null!=b&&(g=f.ba(),d.fa(g)));if(2>e.g.length)throw Error("The string supplied is too short to be a phone number");null!=f&&(g=new l,c=new l(e.toString()),ab(c,f,g),f=T(this,c.toString(),f,-1),2!=f&&4!=f&&5!=f&&(e=c));c=e.toString();e=c.length;if(2>e)throw Error("The string supplied is too short to be a phone number");if(17<e)throw Error("The string supplied is too long to be a phone number");
if(1<c.length&&"0"==c.charAt(0)){r(d,4,!0);for(e=1;e<c.length-1&&"0"==c.charAt(e);)e++;1!=e&&r(d,8,e)}r(d,2,parseInt(c,10));return d};function L(a,b){var c="string"==typeof a?b.match("^(?:"+a+")$"):b.match(a);return c&&c[0].length==b.length?!0:!1};function bb(a){this.ya="\u2008";this.oa=new RegExp(this.ya);this.pa="";this.aa=new l;this.ga="";this.s=new l;this.ca=new l;this.u=!0;this.ja=this.da=this.ta=!1;this.xa=I.Ba();this.ea=0;this.c=new l;this.na=!1;this.m="";this.b=new l;this.i=[];this.qa=a;this.Ea=this.l=cb(this,this.qa)}var db=new D;r(db,11,"NA");
var eb=RegExp("^[-x\u2010-\u2015\u2212\u30fc\uff0d-\uff0f \u00a0\u00ad\u200b\u2060\u3000()\uff08\uff09\uff3b\uff3d.\\[\\]/~\u2053\u223c\uff5e]*(\\$\\d[-x\u2010-\u2015\u2212\u30fc\uff0d-\uff0f \u00a0\u00ad\u200b\u2060\u3000()\uff08\uff09\uff3b\uff3d.\\[\\]/~\u2053\u223c\uff5e]*)+$"),fb=/[- ]/;function cb(a,b){var c=a.xa;c=N(b)?Ya(c,b):0;c=Q(a.xa,P(c));return null!=c?c:db}
function gb(a){for(var b=a.i.length,c=0;c<b;++c){var d=a.i[c],e=v(d,1);if(a.ga==e)return!1;var f=a;var g=d,h=v(g,1);f.aa.clear();var m=f;g=v(g,2);var y="999999999999999".match(h)[0];y.length<m.b.g.length?m="":(h=y.replace(new RegExp(h,"g"),g),m=h=h.replace(RegExp("9","g"),m.ya));0<m.length?(f.aa.append(m),f=!0):f=!1;if(f)return a.ga=e,a.na=fb.test(q(d,4)),a.ea=0,!0}return a.u=!1}
function hb(a,b){for(var c=[],d=b.length-3,e=a.i.length,f=0;f<e;++f){var g=a.i[f];0==w(g,3)?c.push(a.i[f]):(g=q(g,3,Math.min(d,w(g,3)-1)),0==b.search(g)&&c.push(a.i[f]))}a.i=c}bb.prototype.clear=function(){this.pa="";this.s.clear();this.ca.clear();this.aa.clear();this.ea=0;this.ga="";this.c.clear();this.m="";this.b.clear();this.u=!0;this.ja=this.da=this.ta=!1;this.i=[];this.na=!1;this.l!=this.Ea&&(this.l=cb(this,this.qa))};
function ib(a,b){a.s.append(b);var c=b;if(Ea.test(c)||1==a.s.g.length&&Da.test(c)){c=b;if("+"==c){var d=c;a.ca.append(c)}else d=Aa[c],a.ca.append(d),a.b.append(d);b=d}else a.u=!1,a.ta=!0;if(!a.u){if(!a.ta)if(jb(a)){if(kb(a))return lb(a)}else if(0<a.m.length&&(c=a.b.toString(),a.b.clear(),a.b.append(a.m),a.b.append(c),c=a.c.toString(),d=c.lastIndexOf(a.m),a.c.clear(),a.c.append(c.substring(0,d))),a.m!=mb(a))return a.c.append(" "),lb(a);return a.s.toString()}switch(a.ca.g.length){case 0:case 1:case 2:return a.s.toString();
case 3:if(jb(a))a.ja=!0;else return a.m=mb(a),nb(a);default:if(a.ja)return kb(a)&&(a.ja=!1),a.c.toString()+a.b.toString();if(0<a.i.length){c=ob(a,b);d=pb(a);if(0<d.length)return d;hb(a,a.b.toString());return gb(a)?qb(a):a.u?U(a,c):a.s.toString()}return nb(a)}}function lb(a){a.u=!0;a.ja=!1;a.i=[];a.ea=0;a.aa.clear();a.ga="";return nb(a)}
function pb(a){for(var b=a.b.toString(),c=a.i.length,d=0;d<c;++d){var e=a.i[d],f=v(e,1);if((new RegExp("^(?:"+f+")$")).test(b)&&(a.na=fb.test(q(e,4)),e=b.replace(new RegExp(f,"g"),q(e,2)),e=U(a,e),M(e,Ba)==a.ca))return e}return""}function U(a,b){var c=a.c.g.length;return a.na&&0<c&&" "!=a.c.toString().charAt(c-1)?a.c+" "+b:a.c+b}
function nb(a){var b=a.b.toString();if(3<=b.length){for(var c=a.da&&0==a.m.length&&0<w(a.l,20)?t(a.l,20):t(a.l,19),d=c.length,e=0;e<d;++e){var f=c[e];0<a.m.length&&Ua(v(f,4))&&!q(f,6)&&!p(f,5)||(0!=a.m.length||a.da||Ua(v(f,4))||q(f,6))&&eb.test(v(f,2))&&a.i.push(f)}hb(a,b);b=pb(a);return 0<b.length?b:gb(a)?qb(a):a.s.toString()}return U(a,b)}function qb(a){var b=a.b.toString(),c=b.length;if(0<c){for(var d="",e=0;e<c;e++)d=ob(a,b.charAt(e));return a.u?U(a,d):a.s.toString()}return a.c.toString()}
function mb(a){var b=a.b.toString(),c=0;if(1!=a.l.za())var d=!1;else d=a.b.toString(),d="1"==d.charAt(0)&&"0"!=d.charAt(1)&&"1"!=d.charAt(1);d?(c=1,a.c.append("1").append(" "),a.da=!0):p(a.l,15)&&(d=new RegExp("^(?:"+q(a.l,15)+")"),d=b.match(d),null!=d&&null!=d[0]&&0<d[0].length&&(a.da=!0,c=d[0].length,a.c.append(b.substring(0,c))));a.b.clear();a.b.append(b.substring(c));return b.substring(0,c)}
function jb(a){var b=a.ca.toString(),c=new RegExp("^(?:\\+|"+q(a.l,11)+")");c=b.match(c);return null!=c&&null!=c[0]&&0<c[0].length?(a.da=!0,c=c[0].length,a.b.clear(),a.b.append(b.substring(c)),a.c.clear(),a.c.append(b.substring(0,c)),"+"!=b.charAt(0)&&a.c.append(" "),!0):!1}function kb(a){if(0==a.b.g.length)return!1;var b=new l,c=Za(a.b,b);if(0==c)return!1;a.b.clear();a.b.append(b.toString());b=P(c);"001"==b?a.l=Q(a.xa,""+c):b!=a.qa&&(a.l=cb(a,b));a.c.append(""+c).append(" ");a.m="";return!0}
function ob(a,b){var c=a.aa.toString();if(0<=c.substring(a.ea).search(a.oa)){var d=c.search(a.oa);c=c.replace(a.oa,b);a.aa.clear();a.aa.append(c);a.ea=d;return c.substring(0,a.ea+1)}1==a.i.length&&(a.u=!1);a.ga="";return a.s.toString()};var V=I.Ba(),rb={e164:0,international:1,national:2,rfc3966:3},sb={FIXED_LINE:0,MOBILE:1,FIXED_LINE_OR_MOBILE:2,TOLL_FREE:3,PREMIUM_RATE:4,SHARED_COST:5,VOIP:6,PERSONAL_NUMBER:7,PAGER:8,UAN:9,VOICEMAIL:10},tb={"Invalid country calling code":"PHONE_INVALID_COUNTRY_CODE","The string supplied is too short to be a phone number":"PHONE_NUMBER_TOO_SHORT","The string supplied is too long to be a phone number":"PHONE_NUMBER_TOO_LONG","The string supplied did not seem to be a phone number":"PHONE_NOT_A_NUMBER",
"Phone number too short after IDD":"PHONE_TOO_SHORT_AFTER_IDD"};function ub(a){if(!vb(a))throw Error("Invalid metadata");var b=a.regionCodes;if(!b||!Array.isArray(b)||!b.length)throw Error("Invalid metadata");if(!vb(a.countryCodeToRegionCodeMap)||!vb(a.countryToMetadata))throw Error("Invalid metadata");}function vb(a){return null!==a&&"[object Object]"===""+a&&a.constructor===Object}function W(a,b){if(-1===b.regionCodes.indexOf(a))throw Error("Metadata not loaded for region: "+a);}
function wb(a){if(null===a)return null;var b={countryCode:a.j[1].toString(),nationalNumber:a.j[2].toString()};if(p(a,4))for(var c=v(a,8),d=0;d<c;d++)b.nationalNumber="0"+b.nationalNumber;void 0!==a.j[3]&&(b.extension=a.j[3]);return b}
function xb(a){var b=new E,c=!1;b.fa(Number(a.countryCode));var d=a.nationalNumber;if("string"===typeof d){for(var e=0;"0"===d.charAt(e);)c=!0,e++;c&&(r(b,4,!0),r(b,8,e));d=Number(d)}r(b,2,d);void 0!==a.extension&&null!==a.extension&&(a=a.extension.toString(),r(b,3,a));return b}
function yb(a){ub(a);return{getSupportedRegions:function(){H(a);return Sa()},getCountryCodeForRegion:function(b){H(a);W(b,a);return N(b)?Ya(V,b):0},countryCodeToRegionCodeMap:function(){H(a);return F},formatPhoneNumber:function(b,c){H(a);try{var d=xb(b)}catch(f){throw Error("Phone object conversion failed: "+f.message);}c=c||{};var e=rb[c.style];if(void 0===e)throw Error("Invalid style property: "+c.style);return V.format(d,e).toString()},validatePhoneNumber:function(b,c){H(a);W(c,a);try{var d=xb(b)}catch(h){throw Error("Phone object conversion failed: "+
h.message);}var e=d,f=e.ba();var g=O(V,f,c);null==g||"001"!=c&&f!=Ya(V,c)?g=!1:(e=Va(e),g=-1!=(S(e,q(g,1))?S(e,q(g,5))?4:S(e,q(g,4))?3:S(e,q(g,6))?5:S(e,q(g,8))?6:S(e,q(g,7))?7:S(e,q(g,21))?8:S(e,q(g,25))?9:S(e,q(g,28))?10:S(e,q(g,2))?q(g,18)||S(e,q(g,3))?2:0:!q(g,18)&&S(e,q(g,3))?1:-1:-1));if(g)return!0;g=d;d=Va(g);g=g.ba();g in F?(g=O(V,g,P(g)),d=T(V,d,g,-1)):d=1;switch(d){case 1:d="PHONE_INVALID_COUNTRY_CODE";break;case 2:d="PHONE_NUMBER_TOO_SHORT";break;case 3:d="PHONE_NUMBER_TOO_LONG";break;
case 5:d="PHONE_NUMBER_INVALID_LENGTH";break;default:d="PHONE_INVALID_FOR_REGION"}return Error(d)},parsePhoneNumber:function(b,c){H(a);W(c,a);try{var d=V.parse(b,c)}catch(e){return Error(tb[e.message])}return wb(d)},getExampleNumberForType:function(b,c){H(a);W(c,a);var d=sb[b];void 0===d&&(d=-1);return wb(Xa(V,c,d))},getAsYouTypeFormatter:function(b){H(a);W(b,a);var c=new bb(b);return{inputDigit:function(d){c.pa=ib(c,d);return c.pa},clear:function(){return c.clear()}}}}}
var X=["createPhoneHandler"],Y=aa;X[0]in Y||"undefined"==typeof Y.execScript||Y.execScript("var "+X[0]);for(var Z;X.length&&(Z=X.shift());)X.length||void 0===yb?Y=Y[Z]&&Y[Z]!==Object.prototype[Z]?Y[Z]:Y[Z]={}:Y[Z]=yb;
