name: Upgrade & Publish

on: [workflow_dispatch]

# https://docs.npmjs.com/trusted-publishers
permissions:
  id-token: write  # Required for OIDC
  contents: write  # Required to push commits or tags

jobs:
  upgrade:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Set up Node
      uses: actions/setup-node@v7
      with:
        node-version: '24'
        registry-url: 'https://registry.npmjs.org'
        package-manager-cache: false  # never use caching in release builds
    - name: Set up Python
      uses: actions/setup-python@v7
      with:
        python-version: '3.x'
    - name: Install
      run: npm i
    - name: Config
      run: |
        git config --local user.email "dwbruhn@users.noreply.github.com"
        git config --local user.name "Daniel Bruhn"
    - name: Upgrade
      run: npm run upgrade
    - name: Version
      run: npm version minor
    - name: Push
      run: |
        git push origin master
        git push origin --tags
    - name: NPM Publish
      run: npm publish --dry-run
